//go:build linux

package netif

import (
	"context"
	"errors"
	"fmt"
	"net"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/vishvananda/netlink"

	"github.com/MustardSeedNetworks/seed/internal/validation"
)

const dhcpCommandTimeout = 30 * time.Second

// netmaskToCIDR converts a dotted decimal netmask to CIDR prefix length.
func netmaskToCIDR(netmask string) (int, error) {
	// Check if it's already a CIDR prefix (e.g., "24")
	var prefix int
	if _, err := fmt.Sscanf(netmask, "%d", &prefix); err == nil {
		if prefix >= 0 && prefix <= ipv4BitLength {
			return prefix, nil
		}
		return 0, fmt.Errorf("invalid CIDR prefix: %d", prefix)
	}

	// Parse as dotted decimal (e.g., "255.255.255.0")
	ip := net.ParseIP(netmask)
	if ip == nil {
		return 0, fmt.Errorf("invalid netmask: %s", netmask)
	}

	ip4 := ip.To4()
	if ip4 == nil {
		return 0, fmt.Errorf("not an IPv4 netmask: %s", netmask)
	}

	// Convert to prefix length
	mask := net.IPMask(ip4)
	ones, bits := mask.Size()
	if bits != ipv4BitLength {
		return 0, fmt.Errorf("invalid netmask: %s", netmask)
	}

	return ones, nil
}

// updateResolvConf updates /etc/resolv.conf with DNS servers.
func updateResolvConf(dnsServers []string) error {
	// Validate all DNS servers before writing to prevent injection
	if err := validation.ValidateDNSServers(dnsServers); err != nil {
		return fmt.Errorf("invalid DNS configuration: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("# Generated by seed\n")
	for _, dns := range dnsServers {
		fmt.Fprintf(&sb, "nameserver %s\n", dns)
	}

	//nolint:gosec // G306: /etc/resolv.conf needs to be world-readable
	return os.WriteFile("/etc/resolv.conf", []byte(sb.String()), 0o644)
}

// configureStaticIPPlatform applies static IP on Linux using netlink.
func configureStaticIPPlatform(iface string, cfg *StaticIPConfig) error {
	if err := validateStaticIP(iface, cfg); err != nil {
		return err
	}
	prefix, err := netmaskToCIDR(cfg.Netmask)
	if err != nil {
		return err
	}
	link, err := netlink.LinkByName(iface)
	if err != nil {
		return fmt.Errorf("interface not found: %w", err)
	}
	if err = replaceIPv4Address(link, cfg.Address, prefix); err != nil {
		return err
	}
	if err = netlink.LinkSetUp(link); err != nil {
		return fmt.Errorf("failed to bring interface up: %w", err)
	}
	if err = configureGateway(link, cfg.Gateway); err != nil {
		return err
	}
	if len(cfg.DNS) > 0 {
		if err = updateResolvConf(cfg.DNS); err != nil {
			return fmt.Errorf("failed to configure DNS: %w", err)
		}
	}
	return nil
}

func validateStaticIP(iface string, cfg *StaticIPConfig) error {
	if err := validation.ValidateInterface(iface); err != nil {
		return fmt.Errorf("invalid interface: %w", err)
	}
	if !validation.IsValidIPv4(cfg.Address) {
		return fmt.Errorf("invalid IP address: %s", cfg.Address)
	}
	if cfg.Gateway != "" && !validation.IsValidIPv4(cfg.Gateway) {
		return fmt.Errorf("invalid gateway address: %s", cfg.Gateway)
	}
	return nil
}

func replaceIPv4Address(link netlink.Link, address string, prefix int) error {
	addrs, err := netlink.AddrList(link, netlink.FAMILY_V4)
	if err != nil {
		return fmt.Errorf("failed to list addresses: %w", err)
	}
	for _, addr := range addrs {
		if deleteErr := netlink.AddrDel(link, &addr); deleteErr != nil {
			return fmt.Errorf("failed to delete address %s: %w", addr.IPNet, deleteErr)
		}
	}
	ipNet := &net.IPNet{IP: net.ParseIP(address), Mask: net.CIDRMask(prefix, ipv4BitLength)}
	if addErr := netlink.AddrAdd(link, &netlink.Addr{IPNet: ipNet}); addErr != nil {
		return fmt.Errorf("failed to add address: %w", addErr)
	}
	return nil
}

func configureGateway(link netlink.Link, gateway string) error {
	if gateway == "" {
		return nil
	}
	routes, _ := netlink.RouteList(nil, netlink.FAMILY_V4)
	for index := range routes {
		if routes[index].Dst == nil {
			_ = netlink.RouteDel(&routes[index])
		}
	}
	route := &netlink.Route{LinkIndex: link.Attrs().Index, Gw: net.ParseIP(gateway)}
	if err := netlink.RouteAdd(route); err != nil {
		return fmt.Errorf("failed to add default gateway: %w", err)
	}
	return nil
}

// configureDHCPPlatform switches to DHCP on Linux.
// Note: DHCP client invocation requires exec as there's no pure Go DHCP client library.
func configureDHCPPlatform(iface string) error {
	// Validate interface name to prevent command injection
	if err := validation.ValidateInterface(iface); err != nil {
		return fmt.Errorf("invalid interface: %w", err)
	}

	if err := runDHCPCommand("dhclient", "-r", iface); err == nil {
		return runDHCPCommand("dhclient", iface)
	}
	if err := runDHCPCommand("dhcpcd", "-k", iface); err == nil {
		return runDHCPCommand("dhcpcd", iface)
	}
	return errors.New("no DHCP client found (tried dhclient, dhcpcd)")
}

func runDHCPCommand(name string, args ...string) error {
	ctx, cancel := context.WithTimeout(context.Background(), dhcpCommandTimeout)
	defer cancel()
	return exec.CommandContext(ctx, name, args...).Run()
}

// setMTUPlatform sets the MTU on Linux using netlink.
func setMTUPlatform(iface string, mtu int) error {
	// Validate interface name
	if err := validation.ValidateInterface(iface); err != nil {
		return fmt.Errorf("invalid interface: %w", err)
	}

	// Get the link
	link, err := netlink.LinkByName(iface)
	if err != nil {
		return fmt.Errorf("interface not found: %w", err)
	}

	// Set the MTU
	if setErr := netlink.LinkSetMTU(link, mtu); setErr != nil {
		return fmt.Errorf("failed to set MTU: %w", setErr)
	}

	return nil
}
