#!/usr/bin/env node
/**
 * gen-types.mjs — generate TypeScript types from the JSON Schemas
 * committed under docs/schemas/api/.
 *
 * The schemas themselves are generated by `make schema` (cmd/seed-schema)
 * from the Go DTOs in internal/api. This script runs json-schema-to-typescript
 * over each schema and writes the result into ui/src/types/generated/.
 *
 * Adding a DTO is a four-step change with all four happening
 * automatically once you've added the Go field + tag:
 *   1. add a schemaTarget entry in cmd/seed-schema/main.go
 *   2. `make schema`
 *   3. `npm run gen-types` (this script)
 *   4. consume the generated type in ui/src/
 *
 * CI gates 2/3 via scripts/check-schema-drift.sh and the sibling
 * scripts/check-types-drift.sh.
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..', '..');
const SCHEMA_DIR = resolve(ROOT, 'docs', 'schemas', 'api');
const OUT_DIR = resolve(ROOT, 'ui', 'src', 'types', 'generated');

const BANNER = `/**
 * AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 *
 * Regenerate with: \`npm run gen-types\` (or \`make schema && npm run gen-types\`
 * after Go DTO changes). The schema source of truth lives at
 * docs/schemas/api/; the Go DTO source lives at internal/api/.
 */
`;

async function main() {
  const entries = await readdir(SCHEMA_DIR);
  const schemas = entries.filter((f) => f.endsWith('.schema.json')).sort();

  if (schemas.length === 0) {
    console.error(`No schemas found in ${SCHEMA_DIR}`);
    process.exit(1);
  }

  await mkdir(OUT_DIR, { recursive: true });

  for (const filename of schemas) {
    const schemaPath = resolve(SCHEMA_DIR, filename);
    const raw = await readFile(schemaPath, 'utf8');

    // Normalize invopop's draft-2020 output for json-schema-to-typescript.
    // invopop emits `{ $id, $ref: "#/$defs/Root", $defs: { Root, Nested, … } }`.
    // j-s-to-ts mishandles that shape: dereferencing the ROOT $ref replaces the
    // whole document with Root's body and discards `$defs`, so any nested ref
    // (e.g. Root.items.$ref → Nested) then dangles and it throws "Refs should
    // have been resolved...". Three in-memory fixes (committed schema files are
    // unchanged, so schema-drift checks are unaffected):
    //   1. `$defs` → `definitions` (the draft-07 key j-s-to-ts resolves best).
    //   2. drop the external `$id` URL so internal refs resolve locally.
    //   3. INLINE the root $ref to the top level while KEEPING `definitions`,
    //      so nested refs still resolve.
    const schema = JSON.parse(
      raw.replaceAll('#/$defs/', '#/definitions/').replaceAll('"$defs"', '"definitions"'),
    );
    delete schema.$id;

    let root = schema;
    if (typeof schema.$ref === 'string' && schema.$ref.startsWith('#/definitions/')) {
      const name = schema.$ref.slice('#/definitions/'.length);
      const defs = { ...schema.definitions };
      const inlined = defs[name];
      delete defs[name]; // avoid a duplicate of the root type
      root = { $schema: schema.$schema, ...inlined };
      if (Object.keys(defs).length > 0) root.definitions = defs;
    }

    const ts = await compile(root, schema.title || filename, {
      bannerComment: '',
      style: { singleQuote: true, semi: true },
      additionalProperties: false,
    });

    const outName = filename.replace(/\.schema\.json$/, '.ts');
    const outPath = resolve(OUT_DIR, outName);
    await writeFile(outPath, BANNER + ts);
    console.error(`wrote ${outPath}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
