package main

// help_completeness_test.go — locks CLI help completeness in CI.
//
// Walks the full cobra command tree and asserts every command has a non-empty
// Short, Long, and Example, and every flag has a non-empty Usage string. This
// pairs with the manual fills in cmd_*.go: if a new command lands without
// help, CI fails here.

import (
	"sort"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func TestCLIHelpCompleteness(t *testing.T) {
	// Commands cobra adds automatically (help) or that we ship without
	// examples by convention (the shell-completion generator's `completion`
	// command).
	exemptExample := map[string]bool{
		"seed help":       true, // auto-generated by cobra
		"seed completion": true, // generated; conventional cobra completion command
	}

	state := newCLIState()
	initCommands(state)

	var gaps []string
	walkCommands(state.rootCmd, func(c *cobra.Command) {
		path := c.CommandPath()
		if c.Short == "" {
			gaps = append(gaps, path+": missing Short")
		}
		if c.Long == "" {
			gaps = append(gaps, path+": missing Long")
		}
		if c.Example == "" && !exemptExample[path] {
			gaps = append(gaps, path+": missing Example")
		}
		c.Flags().VisitAll(func(f *pflag.Flag) {
			if f.Usage == "" {
				gaps = append(gaps, path+" --"+f.Name+": missing flag Usage")
			}
		})
		c.PersistentFlags().VisitAll(func(f *pflag.Flag) {
			if f.Usage == "" {
				gaps = append(gaps, path+" --"+f.Name+": missing persistent-flag Usage")
			}
		})
	})

	if len(gaps) == 0 {
		return
	}
	sort.Strings(gaps)
	t.Fatalf("CLI help completeness gaps (%d):\n  %s", len(gaps), strings.Join(gaps, "\n  "))
}

func walkCommands(c *cobra.Command, fn func(*cobra.Command)) {
	fn(c)
	for _, sub := range c.Commands() {
		walkCommands(sub, fn)
	}
}
