#!/bin/sh
#
# Target networks behind a router, learned rather than typed (seed#2695).
#
#   scripts/e2e-niac-routed.sh [PACK]
#
# Default pack: `hospital`, NIAC's routed site behind an edge router on a
# transit network. Linux only; needs `niac` on PATH, python3 with PyYAML,
# sudo for the network namespace, the veth pair and the two daemons, and the
# UI's node_modules for Playwright.
#
# The pack is generated by NIAC itself (a throwaway daemon on loopback), so
# the scenario under test and the networks the spec expects are one artifact.
# NIAC then runs it in a network namespace behind a veth pair, bound to the
# pack's attachment network in access mode. Seed's end holds one address on
# that transit network and the edge router's own summary route to the site —
# the shape seed#2695 was reported from — and seed starts with a config naming
# only its interface, port and file paths.
# ui/e2e/niac-routed-learned-subnets.spec.ts then saves the SNMP credential,
# asserts the summary is learned from the host route, enters one site network
# by hand, and asserts every other site network is then learned from the SNMP
# tables of a device inside it and that switching them on finds their devices.
set -eu

pack=${1:-hospital}
repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)

if [ "$(uname -s)" != Linux ]; then
  printf '%s\n' 'e2e-niac-routed needs Linux network namespaces' >&2
  exit 2
fi
command -v niac >/dev/null || {
  printf '%s\n' 'niac is not on PATH; install a NIAC release first' >&2
  exit 2
}
python3 -c 'import yaml' 2>/dev/null || {
  printf '%s\n' 'python3 cannot import yaml; install PyYAML (python3-yaml)' >&2
  exit 2
}

run_dir=$(mktemp -d "${TMPDIR:-/tmp}/seed-niac-routed.XXXXXX")
netns=seed-e2r-$$
seed_link=sdr$$
niac_link=nir$$
generator_pid=
niac_pid=
seed_pid=
exit_status=0

free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()'
}

# Each daemon starts under setsid, so it leads its own process group and
# cleanup can reach everything it forked (seed#2420). Not `set -m`: dash
# turns job control off when there is no terminal.
kill_group() {
  sudo kill -TERM -- "-$1" 2>/dev/null || kill -TERM -- "-$1" 2>/dev/null || return 0
  sleep 1
  sudo kill -KILL -- "-$1" 2>/dev/null || true
}

cleanup() {
  exit_status=$?
  for pid in $seed_pid $niac_pid $generator_pid; do
    kill_group "$pid"
  done
  for pid in $seed_pid $niac_pid $generator_pid; do
    wait "$pid" 2>/dev/null || true
  done
  sudo ip netns del "$netns" 2>/dev/null || true
  sudo ip link del "$seed_link" 2>/dev/null || true
  if [ "$exit_status" -ne 0 ]; then
    # The spec polls the API every two seconds, so the tail of seed.log is
    # request lines; those are dropped here and the whole logs are kept.
    kept=${TMPDIR:-/tmp}/seed-niac-routed-logs.$$
    mkdir -p "$kept"
    for log in generator.log niac.log seed.log; do
      sudo cp "$run_dir/$log" "$kept/" 2>/dev/null || true
      printf '\n%s (last 60 lines, requests omitted):\n' "$log" >&2
      sudo grep -v 'msg="http request"' "$run_dir/$log" 2>/dev/null | tail -60 >&2 || true
    done
    sudo chown -R "$(id -u):$(id -g)" "$kept" 2>/dev/null || true
    printf '\nfull logs kept in %s\n' "$kept" >&2
  fi
  sudo rm -rf "$run_dir"
  trap - EXIT HUP INT TERM
  exit "$exit_status"
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

cd "$repo_dir"
if [ "${E2E_SKIP_BUILD:-0}" != 1 ]; then
  make --no-print-directory build-frontend-quiet
  make --no-print-directory build-backend-quiet
fi
[ -x ./seed ] || {
  printf '%s\n' 'seed binary is missing; run without E2E_SKIP_BUILD or build it first' >&2
  exit 1
}

# Packs are generated, not shipped as files, so ask NIAC for one the way its
# UI does. HOME and NIAC_CONFIGS_DIR point into the run directory so the
# throwaway daemon cannot touch this user's library.
generator_port=$(free_port)
generator_url="https://127.0.0.1:$generator_port"
setsid env HOME="$run_dir" NIAC_CONFIGS_DIR="$run_dir/niac-configs" \
  niac daemon --storage disabled --listen "127.0.0.1:$generator_port" \
  --cert-dir "$run_dir/generator-certs" >"$run_dir/generator.log" 2>&1 &
generator_pid=$!
attempt=0
until curl -skf "$generator_url/__version" >/dev/null 2>&1; do
  attempt=$((attempt + 1))
  if [ "$attempt" -gt 120 ] || ! kill -0 "$generator_pid" 2>/dev/null; then
    printf '%s\n' 'the NIAC pack generator did not start within 30 seconds' >&2
    exit 1
  fi
  sleep 0.25
done
curl -skf "$generator_url/api/v1/scenario/packs" >"$run_dir/packs.json"
python3 - "$run_dir/packs.json" "$pack" "$run_dir/request.json" <<'EOF'
import json
import sys

packs_path, wanted, request_path = sys.argv[1:]
packs = json.load(open(packs_path, encoding="utf-8"))
matches = [p for p in packs if p.get("id") == wanted]
if not matches:
    sys.exit(f"NIAC ships no pack {wanted!r}; it has {sorted(p.get('id') for p in packs)}")
json.dump(matches[0]["request"], open(request_path, "w", encoding="utf-8"))
EOF
csrf=$(curl -skf -c "$run_dir/cookies" -b "$run_dir/cookies" "$generator_url/api/v1/csrf-token" |
  python3 -c 'import json, sys; print(json.load(sys.stdin)["token"])')
curl -skf -b "$run_dir/cookies" -X POST -H "X-CSRF-Token: $csrf" \
  -H 'Content-Type: application/json' --data "@$run_dir/request.json" \
  "$generator_url/api/v1/scenario/generate" >"$run_dir/generated.json"
python3 -c 'import json, sys; open(sys.argv[2], "w", encoding="utf-8").write(json.load(open(sys.argv[1], encoding="utf-8"))["content"])' \
  "$run_dir/generated.json" "$run_dir/scenario.yaml"
kill_group "$generator_pid"
wait "$generator_pid" 2>/dev/null || true
generator_pid=

# Everything the wiring and the spec need, read from the generated YAML:
#
#   attachment  the pack's attachment and the VLAN of the network it connects
#   seed        a free address on that transit network, with its prefix
#   gateway     the SNMP-answering device on the transit network
#   community   that device's community
#   route       the edge router's route covering every site network
#   sites       the private site networks, which seed has to learn
#   devices     per site network, the addresses of the devices inside it
#   typed       the one site network the spec enters by hand
#   core        the agent inside it whose address table names the others
#
# A site network is a private (RFC 1918) network other than the transit one.
# Python's is_private also counts the documentation ranges NIAC uses for its
# WAN, so the test is spelled out.
python3 - "$run_dir/scenario.yaml" "$run_dir/topology.txt" <<'EOF'
import ipaddress
import sys

import yaml

scenario_path, env_path = sys.argv[1:]
scenario = yaml.safe_load(open(scenario_path, encoding="utf-8"))
networks = {n["name"]: n for n in scenario.get("networks") or []}
attachments = scenario.get("attachments") or []
if len(attachments) != 1:
    sys.exit(f"expected one attachment, found {len(attachments)}")
attachment = attachments[0]
transit_network = networks[attachment["connect"]]
transit = ipaddress.ip_network(transit_network["subnet"])
vlan = transit_network.get("virtual_vlan")
if vlan is None:
    sys.exit(f"attachment network {transit_network['name']} has no virtual_vlan")

rfc1918 = [ipaddress.ip_network(n) for n in ("10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16")]
sites = []
for network in networks.values():
    subnet = ipaddress.ip_network(network["subnet"])
    if subnet != transit and any(subnet.subnet_of(block) for block in rfc1918):
        sites.append(subnet)
if not sites:
    sys.exit("the pack has no private site network behind its transit network")

used = set()
gateway = community = None
devices = {str(site): [] for site in sites}
for device in scenario.get("devices") or []:
    addresses = [ipaddress.ip_address(a) for a in device.get("ips") or []]
    used.update(addresses)
    agent = device.get("snmp_agent") or {}
    if gateway is None and agent.get("community"):
        on_transit = [a for a in addresses if a in transit]
        if on_transit:
            gateway, community = on_transit[0], agent["community"]
            gateway_routes = [ipaddress.ip_network(r["destination"]) for r in device.get("routes") or []]
    for site in sites:
        inside = [a for a in addresses if a in site]
        if inside:
            devices[str(site)].append(str(inside[0]))
if gateway is None:
    sys.exit(f"no SNMP-answering device has an address on {transit}")

seed = next(a for a in reversed(list(transit.hosts())) if a not in used)
# The host gets the route the edge router itself carries for the site, so the
# host's table and the router's name the same summary and neither names a
# site network.
covering = [r for r in gateway_routes if r.prefixlen > 0 and all(s.subnet_of(r) for s in sites)]
if not covering:
    sys.exit(f"the edge router {gateway} has no route covering every site network")
route = max(covering, key=lambda r: r.prefixlen)

# The network the operator types: the one holding the first site address of
# the SNMP agent with an address in the most site networks — a core switch,
# whose address table names every other site network. The rest are learned.
agents = [
    [a for a in (ipaddress.ip_address(x) for x in d.get("ips") or []) if any(a in s for s in sites)]
    for d in scenario.get("devices") or []
    if (d.get("snmp_agent") or {}).get("community") == community
]
core = max(agents, key=lambda a: len({s for s in sites for x in a if x in s}))
if len({s for s in sites for x in core if x in s}) < 2:
    sys.exit("no SNMP agent inside the site has addresses in more than one site network")
typed = next(s for s in sites if core[0] in s)

site_devices = ";".join(s + "=" + "|".join(d) for s, d in devices.items())
values = [
    attachment["name"],
    vlan,
    f"{seed}/{transit.prefixlen}",
    gateway,
    community,
    route,
    ",".join(str(s) for s in sites),
    site_devices,
    typed,
    core[0],
]
with open(env_path, "w", encoding="utf-8") as env:
    env.writelines(f"{value}\n" for value in values)
EOF
{
  read -r attachment
  read -r vlan
  read -r seed_cidr
  read -r gateway
  read -r community
  read -r route
  read -r sites
  read -r devices
  read -r typed
  read -r core
} <"$run_dir/topology.txt"

sudo ip netns add "$netns"
sudo ip link add "$seed_link" type veth peer name "$niac_link"
sudo ip link set "$niac_link" netns "$netns"
sudo ip netns exec "$netns" ip link set lo up
sudo ip netns exec "$netns" ip link set "$niac_link" up
sudo ip addr add "$seed_cidr" dev "$seed_link"
sudo ip link set "$seed_link" up
sudo ip route add "$route" via "$gateway" dev "$seed_link"

setsid sudo ip netns exec "$netns" niac daemon --once "$niac_link" "$run_dir/scenario.yaml" \
  --attachment "$attachment" --attachment-mode access --access-vlan "$vlan" \
  --attachment-policy "$niac_link=access:$vlan" \
  --storage disabled --cert-dir "$run_dir/niac-certs" >"$run_dir/niac.log" 2>&1 &
niac_pid=$!

attempt=0
until grep -q 'Simulation started' "$run_dir/niac.log" 2>/dev/null; do
  attempt=$((attempt + 1))
  if [ "$attempt" -gt 120 ] || ! kill -0 "$niac_pid" 2>/dev/null; then
    printf '%s\n' 'NIAC did not start its simulation within 60 seconds' >&2
    exit 1
  fi
  sleep 0.5
done

port=$(free_port)
printf '%s\n' \
  "{\"server\":{\"port\":$port},\"interface\":{\"default\":\"$seed_link\",\"fallbacks\":[],\"startup_retries\":0,\"startup_retry_wait\":0},\"database\":{\"path\":\"$run_dir/seed.db\"},\"logging\":{\"file\":\"$run_dir/seed.log\"}}" \
  >"$run_dir/config.json"

# Root for the raw sockets the sweep uses; HOME repointed so the host's own
# licence file cannot change the tier under test (seed#2688). Started from
# the run directory because seed writes its certs/ and data/ relative to the
# working directory, and as root they would land in the checkout.
(
  cd "$run_dir"
  exec setsid sudo env HOME="$run_dir" SEED_LOGIN_MAX_ATTEMPTS=200 \
    "$repo_dir/seed" --config "$run_dir/config.json" >"$run_dir/seed.out" 2>&1
) &
seed_pid=$!

base_url=
attempt=0
while [ "$attempt" -lt 120 ]; do
  offset=0
  while [ "$offset" -le 9 ]; do
    if curl -skf "https://127.0.0.1:$((port + offset))/__version" >/dev/null 2>&1; then
      base_url="https://127.0.0.1:$((port + offset))"
      break 2
    fi
    offset=$((offset + 1))
  done
  kill -0 "$seed_pid" 2>/dev/null || {
    printf '%s\n' 'Seed exited before becoming ready' >&2
    exit 1
  }
  attempt=$((attempt + 1))
  sleep 0.25
done
[ -n "$base_url" ] || {
  printf '%s\n' 'Seed did not become ready within 30 seconds' >&2
  exit 1
}

cd "$repo_dir/ui"
SEED_E2E_NIAC_ROUTED=1 \
SEED_E2E_SNMP_COMMUNITY="$community" \
SEED_E2E_GATEWAY="$gateway" \
SEED_E2E_SITE_ROUTE="$route" \
SEED_E2E_TYPED_NETWORK="$typed" \
SEED_E2E_CORE="$core" \
SEED_E2E_SITE_NETWORKS="$sites" \
SEED_E2E_SITE_DEVICES="$devices" \
E2E_BASE_URL="$base_url" \
PLAYWRIGHT_IGNORE_HTTPS_ERRORS=true \
  node --disable-warning=DEP0205 ./node_modules/playwright/cli.js test \
  e2e/niac-routed-learned-subnets.spec.ts --project=chromium
