#!/bin/sh
#
# SNMP acceptance against NIAC's scenario packs (seed plan S4-2).
#
#   scripts/snmp-acceptance-niac.sh [PACK ...]
#
# Default packs: the six presentation packs (hospital, warehouse, campus,
# retail, manufacturing, service-provider). Linux only; needs `niac` on
# PATH, python3 with PyYAML, Go, and sudo for the network namespaces and
# NIAC.
#
# Each pack is generated by NIAC itself (a throwaway daemon on loopback), so
# the scenario under test and the manifest it is checked against are one
# artifact. NIAC runs the pack in one network namespace, with the pack's
# attachment (a pool of spare ports on an access switch) in access mode on that
# pool's VLAN; the poller runs in a second namespace on the other end of a veth
# pair, with a free address on the network behind the pool and that network's
# router as its default gateway, so every agent in the pack is reached the way
# a probe plugged into a spare access port reaches it. After the manifest's
# neighbour settling time, TestNIACPack (internal/polling/snmp/orchestrator)
# runs seed's ten collectors against every SNMP agent and fails on any count
# that disagrees with the manifest's expectedObservations, or on any collector
# that errors against an agent; then it runs seed's topology reconcilers over
# what the collectors stored and fails on any link between two agents that
# the pack does not author, or that it authors and seed does not draw. Last,
# NIAC takes one interface down (a behaviour timeline added to the pack, due
# a minute after that poll should be done), every agent's interface table is
# polled again, and seed's alert pipeline must raise exactly one alert: that
# interface going down.
set -eu

repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
if [ "$#" -eq 0 ]; then
  set -- hospital warehouse campus retail manufacturing service-provider
fi

if [ "$(uname -s)" != Linux ]; then
  printf '%s\n' 'snmp-acceptance-niac needs Linux network namespaces' >&2
  exit 2
fi
# Resolved once: the run leg goes through sudo, whose secure_path can find a
# different niac from the one that generated the pack (seed#2984).
niac_bin=$(command -v niac) || {
  printf '%s\n' 'niac is not on PATH; install a NIAC release first' >&2
  exit 2
}
printf 'using %s (%s)\n' "$niac_bin" "$("$niac_bin" --version)"
python3 -c 'import yaml' 2>/dev/null || {
  printf '%s\n' 'python3 cannot import yaml; install PyYAML (python3-yaml)' >&2
  exit 2
}

run_dir=$(mktemp -d "${TMPDIR:-/tmp}/seed-snmp-acceptance.XXXXXX")
niac_ns=seed-sa-niac-$$
poll_ns=seed-sa-poll-$$
poll_link=sap$$
niac_link=san$$
generator_pid=
niac_pid=
exit_status=0

free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()'
}

# Each daemon starts under setsid, so it leads its own process group and
# cleanup can reach everything it forked (seed#2420). Not `set -m`: dash
# turns job control off when there is no terminal.
kill_group() {
  sudo kill -TERM -- "-$1" 2>/dev/null || kill -TERM -- "-$1" 2>/dev/null || return 0
  sleep 1
  sudo kill -KILL -- "-$1" 2>/dev/null || true
}

stop_pack() {
  if [ -n "$niac_pid" ]; then
    kill_group "$niac_pid"
    wait "$niac_pid" 2>/dev/null || true
    niac_pid=
  fi
  sudo ip netns del "$niac_ns" 2>/dev/null || true
  sudo ip netns del "$poll_ns" 2>/dev/null || true
}

cleanup() {
  exit_status=$?
  stop_pack
  if [ -n "$generator_pid" ]; then
    kill_group "$generator_pid"
    wait "$generator_pid" 2>/dev/null || true
  fi
  if [ "$exit_status" -ne 0 ]; then
    kept=${TMPDIR:-/tmp}/seed-snmp-acceptance-logs.$$
    mkdir -p "$kept"
    sudo cp "$run_dir"/*.log "$kept/" 2>/dev/null || true
    sudo chown -R "$(id -u):$(id -g)" "$kept" 2>/dev/null || true
    printf '\nlogs kept in %s\n' "$kept" >&2
  fi
  sudo rm -rf "$run_dir"
  trap - EXIT HUP INT TERM
  exit "$exit_status"
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

cd "$repo_dir"
go test -c -tags niacacceptance -o "$run_dir/acceptance.test" ./internal/polling/snmp/orchestrator

# Packs are generated, not shipped as files, so ask NIAC for them the way its
# UI does. HOME and NIAC_CONFIGS_DIR point into the run directory so the
# throwaway daemon cannot touch this user's library.
generator_port=$(free_port)
generator_url="https://127.0.0.1:$generator_port"
setsid env HOME="$run_dir" NIAC_CONFIGS_DIR="$run_dir/niac-configs" \
  "$niac_bin" daemon --storage disabled --listen "127.0.0.1:$generator_port" \
  --cert-dir "$run_dir/generator-certs" >"$run_dir/generator.log" 2>&1 &
generator_pid=$!
attempt=0
until curl -skf "$generator_url/__version" >/dev/null 2>&1; do
  attempt=$((attempt + 1))
  if [ "$attempt" -gt 120 ] || ! kill -0 "$generator_pid" 2>/dev/null; then
    printf '%s\n' 'the NIAC pack generator did not start within 30 seconds' >&2
    exit 1
  fi
  sleep 0.25
done
curl -skf "$generator_url/api/v1/scenario/packs" >"$run_dir/packs.json"
csrf=$(curl -skf -c "$run_dir/cookies" -b "$run_dir/cookies" "$generator_url/api/v1/csrf-token" |
  python3 -c 'import json, sys; print(json.load(sys.stdin)["token"])')
for pack in "$@"; do
  python3 - "$run_dir/packs.json" "$pack" "$run_dir/$pack.request.json" <<'EOF'
import json
import sys

packs_path, wanted, request_path = sys.argv[1:]
packs = json.load(open(packs_path, encoding="utf-8"))
matches = [p for p in packs if p.get("id") == wanted]
if not matches:
    sys.exit(f"NIAC ships no pack {wanted!r}; it has {sorted(p.get('id') for p in packs)}")
json.dump(matches[0]["request"], open(request_path, "w", encoding="utf-8"))
EOF
  curl -skf -b "$run_dir/cookies" -X POST -H "X-CSRF-Token: $csrf" \
    -H 'Content-Type: application/json' --data "@$run_dir/$pack.request.json" \
    "$generator_url/api/v1/scenario/generate" >"$run_dir/$pack.generated.json"
done
kill_group "$generator_pid"
wait "$generator_pid" 2>/dev/null || true
generator_pid=

failed=
for pack in "$@"; do
  printf '\n== %s\n' "$pack"
  pack_started=$(date +%s)

  # From the generated pack: the scenario YAML, the manifest, the agents to
  # poll, and the wiring. The pool's ports share one access VLAN; the network
  # behind them is the one on that VLAN with an address in the pool switch's
  # broadcast domain, as NIAC resolves it. The poller takes the last free
  # address on that network; its gateway is the device there that carries
  # routes.
  python3 - "$run_dir" "$pack" <<'EOF'
import ipaddress
import json
import sys

import yaml

run_dir, pack = sys.argv[1:]
generated = json.load(open(f"{run_dir}/{pack}.generated.json", encoding="utf-8"))
json.dump(generated["manifest"], open(f"{run_dir}/{pack}.manifest.json", "w", encoding="utf-8"))

scenario = yaml.safe_load(generated["content"])
if "behavior_timelines" in scenario:
    sys.exit("the pack authors behaviour timelines; the fault this run adds would join them")
devices = {d["name"]: d for d in scenario.get("devices") or []}
attachments = scenario.get("attachments") or []
if len(attachments) != 1:
    sys.exit(f"expected one attachment, found {len(attachments)}")
attachment = attachments[0]
switch = devices[attachment["at"]["device"]]
ports = {i["name"]: i for i in switch.get("interfaces") or []}
port_vlans = {tuple(ports[p].get("vlans") or ()) for p in attachment["at"]["ports"]}
if len(port_vlans) != 1 or len(next(iter(port_vlans))) != 1:
    sys.exit(f"pool ports on {switch['name']} carry {sorted(port_vlans)}, not one access VLAN")
(vlan,) = next(iter(port_vlans))

links = {}
for device in devices.values():
    for trunk in device.get("trunk_ports") or []:
        if vlan in (trunk.get("vlans") or []) and not trunk.get("fdb_only"):
            links.setdefault(device["name"], set()).add(trunk["remote_device"])
            links.setdefault(trunk["remote_device"], set()).add(device["name"])
domain, frontier = {switch["name"]}, [switch["name"]]
while frontier:
    for peer in links.get(frontier.pop(), ()):
        if peer not in domain:
            domain.add(peer)
            frontier.append(peer)
in_domain = {ipaddress.ip_address(a) for name in domain for a in devices[name].get("ips") or []}
candidates = [
    ipaddress.ip_network(n["subnet"]) for n in scenario.get("networks") or []
    if n.get("virtual_vlan") == vlan and any(a in ipaddress.ip_network(n["subnet"]) for a in in_domain)
]
if len(candidates) != 1:
    sys.exit(f"VLAN {vlan} behind {switch['name']} resolves to {len(candidates)} networks, not one")
access = candidates[0]

agents, used, gateway = [], set(), None
for device in scenario.get("devices") or []:
    addresses = [ipaddress.ip_address(a) for a in device.get("ips") or []]
    used.update(addresses)
    agent = device.get("snmp_agent") or {}
    if agent and addresses:
        agents.append({
            "name": device["name"],
            "address": str(addresses[0]),
            "community": agent.get("community", ""),
        })
    if gateway is None and device.get("routes"):
        on_access = [a for a in addresses if a in access]
        if on_access:
            gateway = on_access[0]
if gateway is None:
    sys.exit(f"no device on {access} carries routes")
# The links seed's topology can see: a cable or a learned endpoint between two
# devices seed polls. One pair, however many cables join it.
agent_names = {agent["name"] for agent in agents}
agent_links = sorted({
    tuple(sorted((device["name"], trunk["remote_device"])))
    for device in scenario.get("devices") or []
    for trunk in device.get("trunk_ports") or []
    if device["name"] in agent_names and trunk["remote_device"] in agent_names
})
poller = next(a for a in reversed(list(access.hosts())) if a not in used)
settle = generated["manifest"].get("timing", {}).get("neighborsStableAfterSeconds", 0)

# The fault: the first interface that is up on a device seed polls, with an
# address on a subnet that holds no polled address. Losing it cuts the poller
# off from no agent, which the test's second poll of every agent confirms. In
# a routed pack NIAC can fault only addressed interfaces (niac-go#2482). It is
# due a minute after the neighbours settle; the poll before it takes about
# fifteen seconds.
polled = {ipaddress.ip_address(agent["address"]) for agent in agents}
fault = next((
    {"device": device["name"], "interface": interface["name"]}
    for device in scenario.get("devices") or []
    if device.get("snmp_agent") and device.get("ips")
    for interface in device.get("interfaces") or []
    if interface.get("address")
    and not any(a in ipaddress.ip_interface(interface["address"]).network for a in polled)
    and interface.get("admin_status", "up") == "up"
    and interface.get("oper_status", "up") == "up"
), None)
if fault is None:
    sys.exit("no polled device has an up interface off every polled subnet to take down")
fault_offset = settle + 60
timeline = {"behavior_timelines": [{
    "name": "seed-alert-consumer",
    "start_offset_ms": fault_offset * 1000,
    "repeat_count": 1,
    "phases": [{
        "name": "link-down",
        "duration_ms": 600000,
        "faults": [{**fault, "type": "link_down", "value": 1}],
    }],
}]}
with open(f"{run_dir}/{pack}.yaml", "w", encoding="utf-8") as config:
    config.write(generated["content"].rstrip("\n") + "\n")
    config.write(yaml.safe_dump(timeline, sort_keys=False))

json.dump({"pack": pack, "agents": agents, "links": agent_links, "fault": fault}, open(f"{run_dir}/{pack}.targets.json", "w", encoding="utf-8"))
with open(f"{run_dir}/{pack}.wiring", "w", encoding="utf-8") as wiring:
    for value in (attachment["name"], vlan, f"{poller}/{access.prefixlen}", gateway, settle, fault_offset):
        wiring.write(f"{value}\n")
EOF
  {
    read -r attachment
    read -r vlan
    read -r poller_cidr
    read -r gateway
    read -r settle
    read -r fault_offset
  } <"$run_dir/$pack.wiring"

  sudo ip netns add "$niac_ns"
  sudo ip netns add "$poll_ns"
  sudo ip link add "$poll_link" netns "$poll_ns" type veth peer name "$niac_link" netns "$niac_ns"
  sudo ip netns exec "$niac_ns" ip link set lo up
  sudo ip netns exec "$niac_ns" ip link set "$niac_link" up
  sudo ip netns exec "$poll_ns" ip link set lo up
  sudo ip netns exec "$poll_ns" ip addr add "$poller_cidr" dev "$poll_link"
  sudo ip netns exec "$poll_ns" ip link set "$poll_link" up
  sudo ip netns exec "$poll_ns" ip route add default via "$gateway" dev "$poll_link"

  setsid sudo ip netns exec "$niac_ns" "$niac_bin" daemon --once "$niac_link" "$run_dir/$pack.yaml" \
    --attachment "$attachment" --attachment-mode access --access-vlan "$vlan" \
    --attachment-policy "$niac_link=access:$vlan" \
    --storage disabled --cert-dir "$run_dir/niac-certs" >"$run_dir/$pack.niac.log" 2>&1 &
  niac_pid=$!
  attempt=0
  until grep -q 'Simulation started' "$run_dir/$pack.niac.log" 2>/dev/null; do
    attempt=$((attempt + 1))
    if [ "$attempt" -gt 120 ] || ! kill -0 "$niac_pid" 2>/dev/null; then
      printf '%s\n' "NIAC did not start $pack within 60 seconds" >&2
      exit 1
    fi
    sleep 0.5
  done
  # The timeline's clock started before NIAC logged the start, so this is no
  # earlier than the fault.
  fault_at=$(($(date +%s) + fault_offset))
  # Neighbour tables are complete only once every advertiser has sent at
  # least once; the manifest says how long that takes for this pack.
  sleep "$settle"

  # The test runs as the invoking user inside the poller's namespace: it
  # needs no privilege, only the route. It leaves its own MAC out of the pool
  # switch's FDB, which the manifest does not count.
  poller_mac=$(sudo ip netns exec "$poll_ns" cat "/sys/class/net/$poll_link/address")
  if sudo ip netns exec "$poll_ns" sudo -u "$(id -un)" env \
    SEED_NIAC_TARGETS="$run_dir/$pack.targets.json" \
    SEED_NIAC_MANIFEST="$run_dir/$pack.manifest.json" \
    SEED_NIAC_POLLER_MAC="$poller_mac" \
    SEED_NIAC_FAULT_AT="$fault_at" \
    "$run_dir/acceptance.test" -test.run '^TestNIACPack$' -test.v -test.count=1 \
    >"$run_dir/$pack.acceptance.log" 2>&1 &&
    # A -test.run pattern that matches nothing also exits 0.
    grep -q '^--- PASS: TestNIACPack ' "$run_dir/$pack.acceptance.log"; then
    result=PASS
  else
    result=FAIL
    failed="$failed $pack"
  fi
  grep -E 'found|findings|manifest promises|collect failed|topology|alerts|baseline done' "$run_dir/$pack.acceptance.log" | sed 's/^ *//' || true
  printf '%s: %s in %ss\n' "$pack" "$result" "$(($(date +%s) - pack_started))"
  stop_pack
done

if [ -n "$failed" ]; then
  printf '\nfindings on:%s\n' "$failed" >&2
  exit 1
fi
printf '\nzero findings on %s pack(s)\n' "$#"
