#!/bin/sh
#
# SNMP acceptance against NIAC's scenario packs (seed plan S4-2).
#
#   scripts/snmp-acceptance-niac.sh [PACK ...]
#
# Default packs: the six presentation packs (hospital, warehouse, campus,
# retail, manufacturing, service-provider). Linux only; needs `niac` on
# PATH, python3 with PyYAML, Go, and sudo for the network namespaces and
# NIAC.
#
# Each pack is generated by NIAC itself (a throwaway daemon on loopback), so
# the scenario under test and the manifest it is checked against are one
# artifact. NIAC runs the pack in one network namespace, bound to the pack's
# attachment network in access mode; the poller runs in a second namespace on
# the other end of a veth pair, with a free address on that network and the
# pack's edge router as its default gateway, so every agent in the pack is
# reached the way a probe on the lab transit reaches it. After the manifest's
# neighbour settling time, TestNIACPackObservations
# (internal/polling/snmp/orchestrator) runs seed's ten collectors against
# every SNMP agent and fails on any count that disagrees with the manifest's
# expectedObservations, or on any collector that errors against an agent.
set -eu

repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
if [ "$#" -eq 0 ]; then
  set -- hospital warehouse campus retail manufacturing service-provider
fi

if [ "$(uname -s)" != Linux ]; then
  printf '%s\n' 'snmp-acceptance-niac needs Linux network namespaces' >&2
  exit 2
fi
command -v niac >/dev/null || {
  printf '%s\n' 'niac is not on PATH; install a NIAC release first' >&2
  exit 2
}
python3 -c 'import yaml' 2>/dev/null || {
  printf '%s\n' 'python3 cannot import yaml; install PyYAML (python3-yaml)' >&2
  exit 2
}

run_dir=$(mktemp -d "${TMPDIR:-/tmp}/seed-snmp-acceptance.XXXXXX")
niac_ns=seed-sa-niac-$$
poll_ns=seed-sa-poll-$$
poll_link=sap$$
niac_link=san$$
generator_pid=
niac_pid=
exit_status=0

free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()'
}

# Each daemon starts under setsid, so it leads its own process group and
# cleanup can reach everything it forked (seed#2420). Not `set -m`: dash
# turns job control off when there is no terminal.
kill_group() {
  sudo kill -TERM -- "-$1" 2>/dev/null || kill -TERM -- "-$1" 2>/dev/null || return 0
  sleep 1
  sudo kill -KILL -- "-$1" 2>/dev/null || true
}

stop_pack() {
  if [ -n "$niac_pid" ]; then
    kill_group "$niac_pid"
    wait "$niac_pid" 2>/dev/null || true
    niac_pid=
  fi
  sudo ip netns del "$niac_ns" 2>/dev/null || true
  sudo ip netns del "$poll_ns" 2>/dev/null || true
}

cleanup() {
  exit_status=$?
  stop_pack
  if [ -n "$generator_pid" ]; then
    kill_group "$generator_pid"
    wait "$generator_pid" 2>/dev/null || true
  fi
  if [ "$exit_status" -ne 0 ]; then
    kept=${TMPDIR:-/tmp}/seed-snmp-acceptance-logs.$$
    mkdir -p "$kept"
    sudo cp "$run_dir"/*.log "$kept/" 2>/dev/null || true
    sudo chown -R "$(id -u):$(id -g)" "$kept" 2>/dev/null || true
    printf '\nlogs kept in %s\n' "$kept" >&2
  fi
  sudo rm -rf "$run_dir"
  trap - EXIT HUP INT TERM
  exit "$exit_status"
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

cd "$repo_dir"
go test -c -tags niacacceptance -o "$run_dir/acceptance.test" ./internal/polling/snmp/orchestrator

# Packs are generated, not shipped as files, so ask NIAC for them the way its
# UI does. HOME and NIAC_CONFIGS_DIR point into the run directory so the
# throwaway daemon cannot touch this user's library.
generator_port=$(free_port)
generator_url="https://127.0.0.1:$generator_port"
setsid env HOME="$run_dir" NIAC_CONFIGS_DIR="$run_dir/niac-configs" \
  niac daemon --storage disabled --listen "127.0.0.1:$generator_port" \
  --cert-dir "$run_dir/generator-certs" >"$run_dir/generator.log" 2>&1 &
generator_pid=$!
attempt=0
until curl -skf "$generator_url/__version" >/dev/null 2>&1; do
  attempt=$((attempt + 1))
  if [ "$attempt" -gt 120 ] || ! kill -0 "$generator_pid" 2>/dev/null; then
    printf '%s\n' 'the NIAC pack generator did not start within 30 seconds' >&2
    exit 1
  fi
  sleep 0.25
done
curl -skf "$generator_url/api/v1/scenario/packs" >"$run_dir/packs.json"
csrf=$(curl -skf -c "$run_dir/cookies" -b "$run_dir/cookies" "$generator_url/api/v1/csrf-token" |
  python3 -c 'import json, sys; print(json.load(sys.stdin)["token"])')
for pack in "$@"; do
  python3 - "$run_dir/packs.json" "$pack" "$run_dir/$pack.request.json" <<'EOF'
import json
import sys

packs_path, wanted, request_path = sys.argv[1:]
packs = json.load(open(packs_path, encoding="utf-8"))
matches = [p for p in packs if p.get("id") == wanted]
if not matches:
    sys.exit(f"NIAC ships no pack {wanted!r}; it has {sorted(p.get('id') for p in packs)}")
json.dump(matches[0]["request"], open(request_path, "w", encoding="utf-8"))
EOF
  curl -skf -b "$run_dir/cookies" -X POST -H "X-CSRF-Token: $csrf" \
    -H 'Content-Type: application/json' --data "@$run_dir/$pack.request.json" \
    "$generator_url/api/v1/scenario/generate" >"$run_dir/$pack.generated.json"
done
kill_group "$generator_pid"
wait "$generator_pid" 2>/dev/null || true
generator_pid=

failed=
for pack in "$@"; do
  printf '\n== %s\n' "$pack"

  # From the generated pack: the scenario YAML, the manifest, the agents to
  # poll, and the wiring. The poller takes the last free address on the
  # attachment network; its gateway is the device on that network that
  # carries routes, which is the pack's edge router.
  python3 - "$run_dir" "$pack" <<'EOF'
import ipaddress
import json
import sys

import yaml

run_dir, pack = sys.argv[1:]
generated = json.load(open(f"{run_dir}/{pack}.generated.json", encoding="utf-8"))
open(f"{run_dir}/{pack}.yaml", "w", encoding="utf-8").write(generated["content"])
json.dump(generated["manifest"], open(f"{run_dir}/{pack}.manifest.json", "w", encoding="utf-8"))

scenario = yaml.safe_load(generated["content"])
networks = {n["name"]: n for n in scenario.get("networks") or []}
attachments = scenario.get("attachments") or []
if len(attachments) != 1:
    sys.exit(f"expected one attachment, found {len(attachments)}")
attachment = attachments[0]
transit_network = networks[attachment["connect"]]
transit = ipaddress.ip_network(transit_network["subnet"])
vlan = transit_network.get("virtual_vlan")
if vlan is None:
    sys.exit(f"attachment network {transit_network['name']} has no virtual_vlan")

agents, used, gateway = [], set(), None
for device in scenario.get("devices") or []:
    addresses = [ipaddress.ip_address(a) for a in device.get("ips") or []]
    used.update(addresses)
    agent = device.get("snmp_agent") or {}
    if agent and addresses:
        agents.append({
            "name": device["name"],
            "address": str(addresses[0]),
            "community": agent.get("community", ""),
        })
    if gateway is None and device.get("routes"):
        on_transit = [a for a in addresses if a in transit]
        if on_transit:
            gateway = on_transit[0]
if gateway is None:
    sys.exit(f"no device on {transit} carries routes")
poller = next(a for a in reversed(list(transit.hosts())) if a not in used)
settle = generated["manifest"].get("timing", {}).get("neighborsStableAfterSeconds", 0)

json.dump({"pack": pack, "agents": agents}, open(f"{run_dir}/{pack}.targets.json", "w", encoding="utf-8"))
with open(f"{run_dir}/{pack}.wiring", "w", encoding="utf-8") as wiring:
    for value in (attachment["name"], vlan, f"{poller}/{transit.prefixlen}", gateway, settle):
        wiring.write(f"{value}\n")
EOF
  {
    read -r attachment
    read -r vlan
    read -r poller_cidr
    read -r gateway
    read -r settle
  } <"$run_dir/$pack.wiring"

  sudo ip netns add "$niac_ns"
  sudo ip netns add "$poll_ns"
  sudo ip link add "$poll_link" netns "$poll_ns" type veth peer name "$niac_link" netns "$niac_ns"
  sudo ip netns exec "$niac_ns" ip link set lo up
  sudo ip netns exec "$niac_ns" ip link set "$niac_link" up
  sudo ip netns exec "$poll_ns" ip link set lo up
  sudo ip netns exec "$poll_ns" ip addr add "$poller_cidr" dev "$poll_link"
  sudo ip netns exec "$poll_ns" ip link set "$poll_link" up
  sudo ip netns exec "$poll_ns" ip route add default via "$gateway" dev "$poll_link"

  setsid sudo ip netns exec "$niac_ns" niac daemon --once "$niac_link" "$run_dir/$pack.yaml" \
    --attachment "$attachment" --attachment-mode access --access-vlan "$vlan" \
    --attachment-policy "$niac_link=access:$vlan" \
    --storage disabled --cert-dir "$run_dir/niac-certs" >"$run_dir/$pack.niac.log" 2>&1 &
  niac_pid=$!
  attempt=0
  until grep -q 'Simulation started' "$run_dir/$pack.niac.log" 2>/dev/null; do
    attempt=$((attempt + 1))
    if [ "$attempt" -gt 120 ] || ! kill -0 "$niac_pid" 2>/dev/null; then
      printf '%s\n' "NIAC did not start $pack within 60 seconds" >&2
      exit 1
    fi
    sleep 0.5
  done
  # Neighbour tables are complete only once every advertiser has sent at
  # least once; the manifest says how long that takes for this pack.
  sleep "$settle"

  # The test runs as the invoking user inside the poller's namespace: it
  # needs no privilege, only the route.
  if sudo ip netns exec "$poll_ns" sudo -u "$(id -un)" env \
    SEED_NIAC_TARGETS="$run_dir/$pack.targets.json" \
    SEED_NIAC_MANIFEST="$run_dir/$pack.manifest.json" \
    "$run_dir/acceptance.test" -test.run '^TestNIACPackObservations$' -test.v -test.count=1 \
    >"$run_dir/$pack.acceptance.log" 2>&1; then
    result=PASS
  else
    result=FAIL
    failed="$failed $pack"
  fi
  grep -E 'found|findings|manifest promises|collect failed' "$run_dir/$pack.acceptance.log" | sed 's/^ *//' || true
  printf '%s: %s\n' "$pack" "$result"
  stop_pack
done

if [ -n "$failed" ]; then
  printf '\nfindings on:%s\n' "$failed" >&2
  exit 1
fi
printf '\nzero findings on %s pack(s)\n' "$#"
