// totp.go — RFC 6238 TOTP (time-based one-time password) primitives.
//
// This file wraps github.com/pquerna/otp to provide:
//   - Secret generation (32 bytes of entropy, base32-encoded per RFC 4648)
//   - otpauth:// provisioning URI for authenticator apps
//   - 200x200 PNG QR code rendering for that URI
//   - VerifyTOTP with a ±1 period (30s) skew window and constant-time compare
//
// Wave 3 (task #85) — TOTP MFA + WebAuthn passkeys.

package auth

import (
	"bytes"
	"crypto/subtle"
	"encoding/base32"
	"errors"
	"fmt"
	"image/png"
	"time"

	"github.com/pquerna/otp"
	"github.com/pquerna/otp/totp"
)

// TOTP defaults per RFC 6238 / Google Authenticator compatibility.
const (
	// totpDefaultIssuer is the human-readable issuer string shown in
	// authenticator apps. It also forms part of the provisioning URI
	// "label" so the entry is identified as a Seed credential.
	totpDefaultIssuer = "Seed"

	// totpSecretBytes is the size of the shared secret in bytes
	// before base32 encoding. 32 bytes (256 bits) exceeds RFC 4226
	// recommendations and matches modern best practice.
	totpSecretBytes = 32

	// totpQRCodeSize is the side length in pixels of the generated PNG.
	totpQRCodeSize = 200

	// totpPeriodSeconds is the standard TOTP step size in seconds.
	totpPeriodSeconds = 30

	// totpSkewPeriods is the number of additional ±N periods to accept
	// for clock drift tolerance. 1 means we accept the current code plus
	// the immediately preceding and following codes (a ±30s window).
	totpSkewPeriods uint = 1

	// totpCodeDigits is the number of digits in a TOTP code.
	totpCodeDigits = 6
)

// ErrInvalidTOTPInput is returned when the caller supplies an empty
// secret, an empty code, or a code whose length is obviously wrong.
// It is distinct from a simple "code did not verify" result so callers
// can disambiguate input errors from authentication failures.
var ErrInvalidTOTPInput = errors.New("invalid totp input")

// TOTPSetup carries everything a client needs to enroll a TOTP secret.
//
// Secret is the base32-encoded shared secret (no padding) per RFC 4648
// which is what authenticator apps consume. ProvisioningURI is the
// otpauth:// URI that the QR code encodes — clients can fall back to
// manual entry of the URI or the secret. QRCodePNG is the rendered
// 200x200 PNG containing the same URI for scanning.
type TOTPSetup struct {
	Secret          string
	ProvisioningURI string
	QRCodePNG       []byte
}

// GenerateTOTPSecret creates a new TOTP secret for accountName scoped
// to the given issuer (defaulting to "Seed" when blank). The returned
// TOTPSetup contains the base32 secret, the otpauth:// provisioning
// URI, and a 200x200 PNG QR code of that URI.
//
// The secret is generated by pquerna/otp using crypto/rand — we ask
// for 32 bytes of entropy which becomes a ~52-character base32 string.
func GenerateTOTPSecret(accountName, issuer string) (*TOTPSetup, error) {
	if accountName == "" {
		return nil, fmt.Errorf("%w: account name required", ErrInvalidTOTPInput)
	}
	if issuer == "" {
		issuer = totpDefaultIssuer
	}

	key, err := totp.Generate(totp.GenerateOpts{
		Issuer:      issuer,
		AccountName: accountName,
		SecretSize:  totpSecretBytes,
		Period:      totpPeriodSeconds,
		Digits:      otp.DigitsSix,
		Algorithm:   otp.AlgorithmSHA1, // RFC 6238 default; required for app compatibility
	})
	if err != nil {
		return nil, fmt.Errorf("generate totp secret: %w", err)
	}

	img, err := key.Image(totpQRCodeSize, totpQRCodeSize)
	if err != nil {
		return nil, fmt.Errorf("generate qr image: %w", err)
	}

	var buf bytes.Buffer
	if encErr := png.Encode(&buf, img); encErr != nil {
		return nil, fmt.Errorf("encode qr png: %w", encErr)
	}

	return &TOTPSetup{
		Secret:          key.Secret(),
		ProvisioningURI: key.URL(),
		QRCodePNG:       buf.Bytes(),
	}, nil
}

// VerifyTOTP validates code against secret with a ±1-period (30s)
// skew window to tolerate clock drift between server and client.
//
// The comparison itself is delegated to pquerna/otp which performs a
// constant-time compare of the computed HOTP value against the input.
// We additionally apply a constant-time length check ourselves to
// minimise the leakage from the input-validation step.
//
// Returns (false, nil) for a wrong code; (false, ErrInvalidTOTPInput)
// for empty secret/code; (false, err) only on internal failure.
func VerifyTOTP(secret, code string) (bool, error) {
	return VerifyTOTPAt(secret, code, time.Now())
}

// VerifyTOTPAt is VerifyTOTP but evaluated against a caller-supplied
// "now". It exists so tests can deterministically exercise the ±1
// period skew window without resorting to a package-level clock var.
// Production callers should use VerifyTOTP.
func VerifyTOTPAt(secret, code string, at time.Time) (bool, error) {
	if secret == "" || code == "" {
		return false, ErrInvalidTOTPInput
	}

	// Reject inputs whose length cannot possibly verify. We do both a
	// constant-time byte compare (so we don't leak whether the secret
	// or code was the problem in a side-channel) AND a plain length
	// check (so a degenerate length far outside the byte mask still
	// fails). The byte mask is safe because totpCodeDigits fits in a
	// byte by construction.
	const byteMask = 0xFF
	if subtle.ConstantTimeByteEq(
		byte(len(code)&byteMask), byte(totpCodeDigits&byteMask),
	) != 1 || len(code) != totpCodeDigits {
		return false, nil
	}

	// Sanity check the secret is valid base32 (no-padding). pquerna/otp
	// will return false on invalid secrets but we'd rather surface a
	// clear error than silently report "wrong code".
	if _, err := base32.StdEncoding.WithPadding(base32.NoPadding).
		DecodeString(secret); err != nil {
		return false, fmt.Errorf("%w: malformed secret", ErrInvalidTOTPInput)
	}

	// pquerna may return errors for things like malformed inputs. We
	// fold those into a "not valid" result because the public contract
	// of VerifyTOTP only surfaces ErrInvalidTOTPInput, not arbitrary
	// internal errors from the library.
	valid, _ := totp.ValidateCustom(code, secret, at, totp.ValidateOpts{
		Period:    totpPeriodSeconds,
		Skew:      totpSkewPeriods,
		Digits:    otp.DigitsSix,
		Algorithm: otp.AlgorithmSHA1,
	})
	return valid, nil
}
