package resolve

import (
	"encoding/binary"
	"strings"
	"testing"
)

// decodeNetBIOSName reverses the first-level encoding buildNetBIOSQuery applies:
// each byte becomes two nibbles, each added to 'A'.
func decodeNetBIOSName(t *testing.T, encoded []byte) string {
	t.Helper()
	if len(encoded)%2 != 0 {
		t.Fatalf("encoded name is %d bytes, want an even count", len(encoded))
	}
	out := make([]byte, 0, len(encoded)/2)
	for i := 0; i < len(encoded); i += 2 {
		hi := encoded[i] - 'A'
		lo := encoded[i+1] - 'A'
		out = append(out, hi<<netbiosNibbleShift|lo)
	}
	return string(out)
}

// TestBuildNetBIOSQuery decodes the packet rather than comparing it to a golden
// blob. A golden blob would pin the bytes without saying what they mean, and
// would have to be regenerated by whatever change broke it — which is how a
// wire-format test stops catching wire-format bugs.
func TestBuildNetBIOSQuery(t *testing.T) {
	packet := buildNetBIOSQuery()

	if len(packet) != netbiosQueryPacketSize {
		t.Fatalf("packet is %d bytes, want %d", len(packet), netbiosQueryPacketSize)
	}

	if got := binary.BigEndian.Uint16(packet[0:2]); got != netbiosTransactionID {
		t.Errorf("transaction ID = %#04x, want %#04x", got, netbiosTransactionID)
	}
	if got := binary.BigEndian.Uint16(packet[2:4]); got != netbiosQueryOpcode {
		t.Errorf("flags = %#04x, want %#04x (standard query)", got, netbiosQueryOpcode)
	}
	if got := binary.BigEndian.Uint16(packet[4:6]); got != 1 {
		t.Errorf("question count = %d, want 1", got)
	}
	for name, span := range map[string][2]int{
		"answer RRs": {6, 8}, "authority RRs": {8, 10}, "additional RRs": {10, 12},
	} {
		if got := binary.BigEndian.Uint16(packet[span[0]:span[1]]); got != 0 {
			t.Errorf("%s = %d, want 0 in a query", name, got)
		}
	}

	if packet[12] != 32 {
		t.Errorf("encoded-name length = %d, want 32", packet[12])
	}

	// The wildcard "*" padded with spaces to 15 characters. Getting this wrong
	// means every NBSTAT probe silently asks the wrong question.
	decoded := decodeNetBIOSName(t, packet[13:43])
	if want := "*" + strings.Repeat(" ", netbiosNamePadding); decoded != want {
		t.Errorf("decoded name = %q, want %q", decoded, want)
	}

	if suffix := decodeNetBIOSName(t, packet[43:45]); suffix != "\x00" {
		t.Errorf("decoded suffix = %q, want the workstation suffix 0x00", suffix)
	}
	if packet[45] != 0x00 {
		t.Errorf("name terminator = %#02x, want 0x00", packet[45])
	}
	if got := binary.BigEndian.Uint16(packet[46:48]); got != netbiosQueryTypeNBSTAT {
		t.Errorf("query type = %#04x, want NBSTAT %#04x", got, netbiosQueryTypeNBSTAT)
	}
	if got := binary.BigEndian.Uint16(packet[48:50]); got != netbiosQueryClassIN {
		t.Errorf("query class = %#04x, want IN %#04x", got, netbiosQueryClassIN)
	}
}

// netbiosResponse builds a node-status response whose name list begins at the
// offset parseNetBIOSResponse expects.
func netbiosResponse(entries []struct {
	name   string
	suffix byte
},
) []byte {
	const nameListOffset = 56
	data := make([]byte, nameListOffset, nameListOffset+1+len(entries)*18)
	data = append(data, byte(len(entries)))
	for _, e := range entries {
		padded := e.name + strings.Repeat(" ", 15)
		data = append(data, padded[:15]...)
		data = append(data, e.suffix)
		data = append(data, 0x00, 0x00) // flags
	}
	return data
}

type nbEntry = struct {
	name   string
	suffix byte
}

func TestParseNetBIOSResponse(t *testing.T) {
	for _, tc := range []struct {
		name    string
		data    []byte
		want    string
		wantErr bool
	}{
		{
			name: "a single workstation entry",
			data: netbiosResponse([]nbEntry{{"WORKSTATION1", 0x00}}),
			want: "WORKSTATION1",
		},
		{
			// Suffix 0x00 is the computer name; 0x20 is the file-server service
			// and would be the wrong answer to report as a hostname.
			name: "the workstation suffix wins over a file-server entry",
			data: netbiosResponse([]nbEntry{
				{"WORKGROUP", 0x1E},
				{"FILESERVER", 0x20},
				{"REALNAME", 0x00},
			}),
			want: "REALNAME",
		},
		{
			name: "the first workstation entry wins",
			data: netbiosResponse([]nbEntry{{"FIRST", 0x00}, {"SECOND", 0x00}}),
			want: "FIRST",
		},
		{
			name:    "no workstation entry at all",
			data:    netbiosResponse([]nbEntry{{"WORKGROUP", 0x1E}, {"SERVER", 0x20}}),
			wantErr: true,
		},
		{
			name:    "a response claiming zero names",
			data:    netbiosResponse(nil),
			wantErr: true,
		},
		{
			name:    "a response shorter than the minimum",
			data:    make([]byte, netbiosMinResponseSize-1),
			wantErr: true,
		},
		{
			name:    "no bytes at all",
			data:    nil,
			wantErr: true,
		},
		{
			// A hostile responder can claim more entries than it sends. The
			// parser must not read past the buffer.
			name: "a name count larger than the data present",
			data: func() []byte {
				d := netbiosResponse([]nbEntry{{"TRUNCATED", 0x00}})
				d[56] = 200
				return d
			}(),
			want: "TRUNCATED",
		},
		{
			// Same lie, with nothing after the count to read at all.
			name: "a name count with no entries behind it",
			data: func() []byte {
				d := make([]byte, netbiosMinResponseSize)
				d[56] = 100
				return d
			}(),
			wantErr: true,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := parseNetBIOSResponse(tc.data)
			if tc.wantErr {
				if err == nil {
					t.Fatalf("parseNetBIOSResponse returned %q, want an error", got)
				}
				return
			}
			if err != nil {
				t.Fatalf("parseNetBIOSResponse: %v", err)
			}
			if got != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
			if strings.ContainsAny(got, " \x00") {
				t.Errorf("got %q, which keeps its padding", got)
			}
		})
	}
}

func TestNetBIOSResolverCache(t *testing.T) {
	r := NewNetBIOSResolver()

	if name, ok := r.GetCached("192.168.0.1"); ok {
		t.Errorf("a fresh resolver returned %q for an unseen IP", name)
	}

	r.mu.Lock()
	r.names["192.168.0.1"] = "WORKSTATION1"
	r.mu.Unlock()

	name, ok := r.GetCached("192.168.0.1")
	if !ok || name != "WORKSTATION1" {
		t.Errorf("GetCached = (%q, %v), want (%q, true)", name, ok, "WORKSTATION1")
	}

	r.ClearCache()
	if leftover, stillThere := r.GetCached("192.168.0.1"); stillThere {
		t.Errorf("ClearCache left %q behind", leftover)
	}
}
