// seed-openapi generates docs/openapi.yaml from the route registry in
// internal/api (Server.routes), so the published API description cannot drift
// from the routes the daemon actually serves.
//
// Usage:
//
//	seed-openapi [-source docs/openapi-source.yaml] [-o docs/openapi.yaml]
//
// The registry supplies every path, its methods and its policy — auth, CSRF,
// operator scope, rate limiting and the body cap. The request and response
// schemas are the DTOs of internal/api/apischema, the same registry
// cmd/seed-schema writes docs/schemas/api from, published as components. Prose,
// and which schema each operation carries, come from the source file. The
// document itself is rendered by foundation's shared emitter; this command
// supplies only what is seed's: the registry, the schemas, the source, the
// error envelope and the header.
package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/invopop/jsonschema"
	"gopkg.in/yaml.v3"

	"github.com/MustardSeedNetworks/foundation/pkg/httpserver/route"
	"github.com/MustardSeedNetworks/foundation/pkg/httpserver/route/openapi"

	"github.com/MustardSeedNetworks/seed/internal/api"
	"github.com/MustardSeedNetworks/seed/internal/api/apischema"
)

const header = "# GENERATED by `make openapi` (cmd/seed-openapi) — do not edit.\n" +
	"# Paths and their policy come from the route registry\n" +
	"# (internal/api Server.routes), schemas from internal/api/apischema,\n" +
	"# prose from docs/openapi-source.yaml.\n"

const outputFileMode os.FileMode = 0o600

// The reflector files nested types under $defs; the document files them under
// components.schemas.
const (
	defsRef      = "#/$defs/"
	componentRef = "#/components/schemas/"
)

func main() {
	source := flag.String("source", "docs/openapi-source.yaml", "hand-written preamble and per-operation enrichment")
	out := flag.String("o", "", "output file path; '-' or empty writes to stdout")
	flag.Parse()

	if err := run(*source, *out); err != nil {
		fmt.Fprintf(os.Stderr, "seed-openapi: %v\n", err)
		os.Exit(1)
	}
}

func run(source, out string) error {
	sourceData, err := os.ReadFile(filepath.Clean(source))
	if err != nil {
		return err
	}
	doc, err := generate(sourceData, api.RouteManifest())
	if err != nil {
		return err
	}
	if out == "" || out == "-" {
		_, writeErr := os.Stdout.Write(doc)
		return writeErr
	}
	return writeOutput(out, doc)
}

// writeOutput writes doc to path through an [os.Root] on its directory, so the
// write cannot resolve outside the directory the operator named.
func writeOutput(path string, doc []byte) error {
	root, err := os.OpenRoot(filepath.Dir(path))
	if err != nil {
		return err
	}
	defer func() { _ = root.Close() }()
	return root.WriteFile(filepath.Base(path), doc, outputFileMode)
}

// generate renders the OpenAPI document. Both inputs are explicit so the
// generator is testable without a file or a live server.
func generate(sourceData []byte, routes []route.Policy) ([]byte, error) {
	errSchema, err := errorSchema()
	if err != nil {
		return nil, err
	}
	schemas, err := componentSchemas(apischema.Targets())
	if err != nil {
		return nil, err
	}
	withSchemas, err := addSchemas(sourceData, schemas)
	if err != nil {
		return nil, err
	}
	doc, err := openapi.Generate(withSchemas, routes, openapi.Options{
		Header:      header,
		ErrorSchema: errSchema,
	})
	if err != nil {
		return nil, err
	}
	if refErr := checkRefs(doc); refErr != nil {
		return nil, refErr
	}
	return doc, nil
}

// componentSchemas reflects every registry DTO into a component schema. The
// reflector files a DTO and each type it nests under $defs; those are lifted
// to components and their refs rewritten, so a type shared by several DTOs is
// published once. A name two packages both use is qualified with the package
// name (qos.ListenRequest becomes QosListenRequest), so neither overwrites the
// other.
func componentSchemas(targets []apischema.Target) (map[string]any, error) {
	ambiguous, err := ambiguousNames(targets)
	if err != nil {
		return nil, err
	}
	reflector := apischema.NewReflector()
	reflector.Namer = func(t reflect.Type) string {
		if !ambiguous[t.Name()] {
			return t.Name()
		}
		pkg := t.PkgPath()[strings.LastIndex(t.PkgPath(), "/")+1:]
		return strings.ToUpper(pkg[:1]) + pkg[1:] + t.Name()
	}

	out := map[string]any{}
	for _, target := range targets {
		defs, defsErr := reflectDefs(reflector, target.Value)
		if defsErr != nil {
			return nil, fmt.Errorf("%s: %w", target.Title, defsErr)
		}
		for name, def := range defs {
			mapRefs(def, func(ref string) string { return strings.Replace(ref, defsRef, componentRef, 1) })
			out[name] = def
		}
	}
	return out, nil
}

// ambiguousNames reflects the registry once to record which package each
// type name comes from, and returns the names more than one package uses.
func ambiguousNames(targets []apischema.Target) (map[string]bool, error) {
	packages := map[string]map[string]bool{}
	reflector := apischema.NewReflector()
	reflector.Namer = func(t reflect.Type) string {
		if packages[t.Name()] == nil {
			packages[t.Name()] = map[string]bool{}
		}
		packages[t.Name()][t.PkgPath()] = true
		return t.Name()
	}
	for _, target := range targets {
		if _, err := reflectDefs(reflector, target.Value); err != nil {
			return nil, fmt.Errorf("%s: %w", target.Title, err)
		}
	}
	ambiguous := map[string]bool{}
	for name, pkgs := range packages {
		if len(pkgs) > 1 {
			ambiguous[name] = true
		}
	}
	return ambiguous, nil
}

// reflectDefs returns the $defs of one DTO's schema as plain maps, so
// yaml.Marshal walks them rather than the reflector's ordered-map types.
func reflectDefs(reflector *jsonschema.Reflector, value any) (map[string]any, error) {
	data, err := json.Marshal(reflector.Reflect(value))
	if err != nil {
		return nil, err
	}
	var schema struct {
		Defs map[string]any `json:"$defs"`
	}
	if unmarshalErr := json.Unmarshal(data, &schema); unmarshalErr != nil {
		return nil, unmarshalErr
	}
	return schema.Defs, nil
}

// mapRefs replaces every $ref under node with what fn returns for it.
func mapRefs(node any, fn func(ref string) string) {
	switch n := node.(type) {
	case map[string]any:
		for k, v := range n {
			if ref, isRef := v.(string); isRef && k == "$ref" {
				n[k] = fn(ref)
				continue
			}
			mapRefs(v, fn)
		}
	case []any:
		for _, v := range n {
			mapRefs(v, fn)
		}
	}
}

// addSchemas files the reflected schemas under the source preamble's
// components.schemas. The source may not define one itself: a hand-written
// schema for a reflected name would describe a body the daemon does not send.
func addSchemas(sourceData []byte, schemas map[string]any) ([]byte, error) {
	var source map[string]any
	if err := yaml.Unmarshal(sourceData, &source); err != nil {
		return nil, fmt.Errorf("parsing source: %w", err)
	}
	preamble, _ := source["preamble"].(map[string]any)
	if preamble == nil {
		return nil, errors.New("source has no preamble")
	}
	components, _ := preamble["components"].(map[string]any)
	if components == nil {
		components = map[string]any{}
		preamble["components"] = components
	}
	if _, defined := components["schemas"]; defined {
		return nil, errors.New(
			"source preamble must not define components.schemas: they are reflected from internal/api/apischema",
		)
	}
	components["schemas"] = schemas
	return yaml.Marshal(source)
}

// checkRefs fails on a $ref naming no component: an operation pointing at a
// schema the registry does not publish, typically a renamed DTO.
func checkRefs(doc []byte) error {
	var parsed map[string]any
	if err := yaml.Unmarshal(doc, &parsed); err != nil {
		return err
	}
	components, _ := parsed["components"].(map[string]any)
	schemas, _ := components["schemas"].(map[string]any)
	var dangling []string
	mapRefs(parsed, func(ref string) string {
		name, isComponent := strings.CutPrefix(ref, componentRef)
		if _, published := schemas[name]; !isComponent || !published {
			dangling = append(dangling, ref)
		}
		return ref
	})
	if len(dangling) == 0 {
		return nil
	}
	sort.Strings(dangling)
	return fmt.Errorf("references name no component schema: %s", strings.Join(dangling, ", "))
}

// errorSchema renders api.ErrorResponse — the envelope every writeError call
// and every Registrar refusal produces — reflected from the Go type so the
// document cannot describe fields the daemon does not send.
func errorSchema() (map[string]any, error) {
	reflector := &jsonschema.Reflector{
		ExpandedStruct:            true,
		DoNotReference:            true,
		AllowAdditionalProperties: true,
	}
	// Round-trip through JSON so yaml.Marshal walks plain maps rather than the
	// reflector's ordered-map types.
	data, err := json.Marshal(reflector.Reflect(&api.ErrorResponse{}))
	if err != nil {
		return nil, fmt.Errorf("marshalling the error schema: %w", err)
	}
	var out map[string]any
	if unmarshalErr := json.Unmarshal(data, &out); unmarshalErr != nil {
		return nil, fmt.Errorf("unmarshalling the error schema: %w", unmarshalErr)
	}
	// $schema and $id describe a JSON Schema document; an OpenAPI components
	// entry carries neither.
	delete(out, "$schema")
	delete(out, "$id")
	return out, nil
}
